In [1]:
import numpy as np
import pandas as pd

box = pd.read_csv('./import.io/box_office_results_121515_cleaned.csv', delimiter=',', error_bad_lines = False)

In [2]:
box.rename(columns = {'_num':'list_number', 'title/_text':'btitle', 'opening_date/_text':'opening_date'}, inplace = True)

In [3]:
# replace n/a values with null values
box.total_theatres.replace(['None'], [np.nan], inplace = True)

box['total_gross'].count() # counts number of values in total_theatres
box['total_gross'].isnull().sum() # counts number of null values in total_theatres
print box['total_gross'].count() + box['total_gross'].isnull().sum() # check for total number of data points in total_theatres

16184

In [4]:
# box.total_gross.unique()
# replaces non-numeric values with null values
box.total_gross.replace(['Total Gross / Theaters', 'n/a', 'n/a*'], [np.nan, np.nan, np.nan], inplace = True)

# replaces dollar signs, asterisks, commas, and spaces and converts data into float 
box.total_gross = box.total_gross.str.replace('$','').str.replace('*', '').str.replace(',', '').str.replace(' ', '')
box.total_gross = box.total_gross.convert_objects(convert_numeric=True)

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:7: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

In [5]:
box['total_theatres'].count() # counts number of values in total_theatres
box['total_theatres'].isnull().sum() # counts number of null values in total_theatres
print box['total_theatres'].count() + box['total_theatres'].isnull().sum() # check for total number of data points in total_theatres

16184

In [6]:
# converts total_theatres into numeric
box.total_theatres = box.total_theatres.convert_objects(convert_numeric=True)

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  from ipykernel import kernelapp as app

In [7]:
# groupby opening_gross to see non-conforming variations of data
# box.groupby('opening_gross')['opening_gross'].count()
# replaces non-numeric values with null values
box.opening_gross.replace(['Opening / Theaters', 'n/a'], [np.nan, np.nan], inplace = True)

# replaces dollar signs, asterisks, commas, and spaces and converts data into float 
box.opening_gross = box.opening_gross.str.replace('$','').str.replace('*', '').str.replace(',', '').str.replace(' ', '')
box.opening_gross = box.opening_gross.convert_objects(convert_numeric=True)

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:8: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

In [8]:
# replaces n/a values with null values
# box.groupby('opening_theatres')['opening_theatres'].count()
box.opening_theatres.replace(['n/a'], [np.nan], inplace = True)

# replaces dollar signs, asterisks, commas, and spaces and converts data into float 
box.opening_theatres = box.opening_theatres.str.replace('$','').str.replace('*', '').str.replace(',', '').str.replace(' ', '')
box.opening_theatres = box.opening_theatres.convert_objects(convert_numeric=True)

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:7: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

In [9]:
box.groupby('opening_date')['opening_date'].count()

opening_date
1/1/1983         1
1/1/1984         1
1/1/1993         1
1/1/1999         2
1/1/2000         3
1/1/2002         1
1/1/2003         1
1/10/1986        1
1/10/1992        2
1/10/1997        3
1/10/2003        4
1/10/2014       13
1/11/1985        2
1/11/1991        4
1/11/1995        1
1/11/2002        4
1/11/2006        1
1/11/2008        6
1/11/2012        1
1/11/2013        6
1/12/1990        4
1/12/1996        6
1/12/2000        2
1/12/2001        3
1/12/2007        7
1/12/2018        1
1/13/1984        2
1/13/1989        5
1/13/1993        1
1/13/1995        3
              ...
9/5/2013         1
9/5/2014        19
9/6/1985         1
9/6/1991         2
9/6/1996         4
9/6/2002         7
9/6/2006         2
9/6/2013        26
9/7/1984         2
9/7/1990         1
9/7/2001         7
9/7/2005         1
9/7/2007        13
9/7/2012        14
9/8/1989         1
9/8/1995         6
9/8/2000         9
9/8/2004         1
9/8/2006        11
9/9/1983         2
9/9/1988         4
9/9/1992         1
9/9/1994         3
9/9/2005        13
9/9/2009         3
9/9/2011        18
9/9/2015         3
9/9/2016         1
TBD            173
Winter 2015      1
Name: opening_date, dtype: int64

In [10]:
# box[box['opening_date'].str.contains("2016") == True]
# box.groupby('opening_date')['opening_date'].count()

# replace non-conforming date formats with null values
box.opening_date.replace(['TBD', 'Winter 2015', '2015', '2016', '2017', '2018', '2020'], [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan], inplace = True)
# formats opening date string into datetime format
box['opening_date'] = pd.to_datetime(box['opening_date'], format = "%m/%d/%Y")

In [11]:
# average total gross for films opening after year 2000
round(box.total_gross[box.opening_date > '2000-01-01'].mean(), 0)

16973986.0

In [12]:
# read in the OMDB csv file
omdb = pd.read_csv('./omdbMovies.txt', delimiter='\t', error_bad_lines = False, dtype = object)

Skipping line 193827: expected 21 fields, saw 27

Skipping line 369640: expected 21 fields, saw 22

Skipping line 521337: expected 21 fields, saw 22

Skipping line 611109: expected 21 fields, saw 22

Skipping line 675690: expected 21 fields, saw 22

Skipping line 746112: expected 21 fields, saw 22

Skipping line 757554: expected 21 fields, saw 22

Skipping line 1064760: expected 21 fields, saw 22

In [13]:
omdb.head()

,ID,imdbID,Title,Year,Rating,Runtime,Genre,Released,Director,Writer,...,Metacritic,imdbRating,imdbVotes,Poster,Plot,FullPlot,Language,Country,Awards,lastUpdated
0,1,tt0000001,Carmencita,1894,NOT RATED,1 min,"Documentary, Short",NaN,William K.L. Dickson,NaN,...,NaN,5.8,1087,http://ia.media-imdb.com/images/M/MV5BMjAzNDEw...,Performing on what looks like a small wooden s...,Performing on what looks like a small wooden s...,NaN,USA,NaN,2015-11-09 13:18:05.367000000
1,2,tt0000002,Le clown et ses chiens,1892,NaN,NaN,"Animation, Short",1892-10-28,�mile Reynaud,NaN,...,NaN,6.4,122,NaN,Short film of 300 individually painted images.,Short film of 300 individually painted images.,NaN,France,NaN,2015-08-12 00:06:01.033000000
2,3,tt0000003,Pauvre Pierrot,1892,NaN,4 min,"Animation, Comedy, Short",1892-10-28,�mile Reynaud,NaN,...,NaN,6.7,596,NaN,"One night, Arlequin come to see his lover Colo...","One night, Arlequin come to see his lover Colo...",NaN,France,NaN,2015-10-17 00:09:13.963000000
3,4,tt0000004,Un bon bock,1892,NaN,NaN,"Animation, Short",1892-10-28,�mile Reynaud,NaN,...,NaN,6.6,78,NaN,NaN,NaN,NaN,France,NaN,2015-08-12 00:06:04.267000000
4,5,tt0000005,Blacksmith Scene,1893,UNRATED,1 min,Short,1893-05-09,William K.L. Dickson,NaN,...,NaN,6.2,1234,NaN,Three men hammer on an anvil and pass a bottle...,A stationary camera looks at a large anvil wit...,NaN,USA,1 win.,2015-11-19 01:55:28.163000000

In [14]:
# converts Year column to float, which allows filters and calculations to be made
omdb.Year = omdb.Year.convert_objects(convert_numeric=True)

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  from ipykernel import kernelapp as app

In [15]:
omdb.Year.mean()

1987.0732544561456

In [16]:
omdb[omdb.Title == 'Kate & Leopold']

,ID,imdbID,Title,Year,Rating,Runtime,Genre,Released,Director,Writer,...,Metacritic,imdbRating,imdbVotes,Poster,Plot,FullPlot,Language,Country,Awards,lastUpdated
34994,35423,tt0035423,Kate & Leopold,2001,PG-13,118 min,"Comedy, Fantasy, Romance",2001-12-25,James Mangold,"Steven Rogers (story), James Mangold (screenpl...",...,44,6.3,61093,http://ia.media-imdb.com/images/M/MV5BODU1MzU0...,Kate and her actor brother live in N.Y. in the...,Kate and her actor brother live in N.Y. in the...,"English, French",USA,Nominated for 1 Oscar. Another 1 win & 4 nomin...,2015-12-03 00:58:15.250000000

In [17]:
box[box.btitle == 'Kate and Leopold']

,list_number,btitle,studio,total_gross,total_theatres,opening_gross,opening_theatres,opening_date
7673,7732,Kate and Leopold,Mira.,47121859,2467,9725408,2452,2001-12-25

In [18]:
#  replace titles with '&' with 'and' and string columns with latin equivalents
box.btitle = box.btitle.str.replace('&', 'and')
box.btitle = box.btitle.str.decode('latin-1')
box.btitle = box.btitle.str.encode('utf-8')

# normalize string columns by making lower case
box.btitle = box.btitle.str.lower()
box.studio = box.studio.str.lower()

box.head()

,list_number,btitle,studio,total_gross,total_theatres,opening_gross,opening_theatres,opening_date
0,11,10,wb,74865517,NaN,3526692,706,NaT
1,19,10000 b.c.,wb,94784201,3454,35867488,3410,2008-03-07
2,20,10000 km,bg,12423,11,8941,11,2015-07-10
3,385,after earth,sony,60522097,3401,27520040,3401,2013-05-31
4,10,1000 times good night,fm,53895,24,24120,24,2014-10-24

In [19]:
# create column in Box and OMDB dataframes that cocatenates title and year to use as unique ID
# extract year from opening_date, convert into string and combine with title to create title_year column
box['byear'] = box['opening_date'].dt.year
box['byear'] = box.byear.astype(str)
box['byear'] = box.byear.str.split('.').str[0]
box['title_year'] = box['btitle'] + '|' + box['byear']
box.head()

,list_number,btitle,studio,total_gross,total_theatres,opening_gross,opening_theatres,opening_date,byear,title_year
0,11,10,wb,74865517,NaN,3526692,706,NaT,nan,10|nan
1,19,10000 b.c.,wb,94784201,3454,35867488,3410,2008-03-07,2008,10000 b.c.|2008
2,20,10000 km,bg,12423,11,8941,11,2015-07-10,2015,10000 km|2015
3,385,after earth,sony,60522097,3401,27520040,3401,2013-05-31,2013,after earth|2013
4,10,1000 times good night,fm,53895,24,24120,24,2014-10-24,2014,1000 times good night|2014

In [20]:
# rename OMDB columns and make headers all lowercase
omdb.rename(columns = {'Title':'otitle', 'Year': 'oyear'}, inplace = True)
omdb.columns = map(str.lower, omdb.columns)

# replace '&' with 'and' and replace string columns with latin equivalents
omdb.otitle = omdb.otitle.str.replace('&', 'and')
omdb.otitle = omdb.otitle.str.decode('latin-1')
omdb.otitle = omdb.otitle.str.encode('utf-8')
omdb.director = omdb.director.str.decode('latin-1')
omdb.director = omdb.director.str.encode('utf-8')
omdb.writer = omdb.writer.str.decode('latin-1')
omdb.writer = omdb.writer.str.encode('utf-8')
omdb.cast = omdb.cast.str.decode('latin-1')
omdb.cast = omdb.cast.str.encode('utf-8')

# make all string columns lowercase
omdb.otitle = omdb.otitle.str.lower()
omdb.rating = omdb.rating.str.lower()
omdb.genre = omdb.genre.str.lower()
omdb.director = omdb.director.str.lower()
omdb.writer = omdb.writer.str.lower()
omdb.cast = omdb.cast.str.lower()
omdb.language = omdb.language.str.lower()
omdb.country = omdb.country.str.lower()
omdb.awards = omdb.awards.str.lower()

In [21]:
# rename OMDB columns and convert year into string and combine with title to create title_year column
omdb['oyear'] = omdb.oyear.astype(str)
omdb['oyear'] = omdb.oyear.str.split('.').str[0]
omdb['title_year'] = omdb['otitle'] + '|' + omdb['oyear']
omdb.head()

,id,imdbid,otitle,oyear,rating,runtime,genre,released,director,writer,...,imdbrating,imdbvotes,poster,plot,fullplot,language,country,awards,lastupdated,title_year
0,1,tt0000001,carmencita,1894,not rated,1 min,"documentary, short",NaN,william k.l. dickson,NaN,...,5.8,1087,http://ia.media-imdb.com/images/M/MV5BMjAzNDEw...,Performing on what looks like a small wooden s...,Performing on what looks like a small wooden s...,NaN,usa,NaN,2015-11-09 13:18:05.367000000,carmencita|1894
1,2,tt0000002,le clown et ses chiens,1892,NaN,NaN,"animation, short",1892-10-28,Émile reynaud,NaN,...,6.4,122,NaN,Short film of 300 individually painted images.,Short film of 300 individually painted images.,NaN,france,NaN,2015-08-12 00:06:01.033000000,le clown et ses chiens|1892
2,3,tt0000003,pauvre pierrot,1892,NaN,4 min,"animation, comedy, short",1892-10-28,Émile reynaud,NaN,...,6.7,596,NaN,"One night, Arlequin come to see his lover Colo...","One night, Arlequin come to see his lover Colo...",NaN,france,NaN,2015-10-17 00:09:13.963000000,pauvre pierrot|1892
3,4,tt0000004,un bon bock,1892,NaN,NaN,"animation, short",1892-10-28,Émile reynaud,NaN,...,6.6,78,NaN,NaN,NaN,NaN,france,NaN,2015-08-12 00:06:04.267000000,un bon bock|1892
4,5,tt0000005,blacksmith scene,1893,unrated,1 min,short,1893-05-09,william k.l. dickson,NaN,...,6.2,1234,NaN,Three men hammer on an anvil and pass a bottle...,A stationary camera looks at a large anvil wit...,NaN,usa,1 win.,2015-11-19 01:55:28.163000000,blacksmith scene|1893

In [22]:
# need to save down OMDB filtered film list (e.g. after year 2000, runtime less than 60 mins?)
box_omdb = pd.merge(box, omdb, on = 'title_year', how = 'inner')
box_omdb
# box_omdb.to_csv('box_omdb.csv', delimiter = ',')

,list_number,btitle,studio,total_gross,total_theatres,opening_gross,opening_theatres,opening_date,byear,title_year,...,metacritic,imdbrating,imdbvotes,poster,plot,fullplot,language,country,awards,lastupdated
0,385,after earth,sony,60522097,3401,27520040,3401,2013-05-31,2013,after earth|2013,...,33,4.9,150066,http://ia.media-imdb.com/images/M/MV5BMTY3MzQy...,A crash landing leaves Kitai Raige and his fat...,One thousand years after cataclysmic events fo...,english,usa,3 wins & 7 nominations.,2015-11-24 00:18:05.520000000
1,6817,the hundred-foot journey,bv,54240821,2167,10979290,2023,2014-08-08,2014,the hundred-foot journey|2014,...,55,7.3,44661,http://ia.media-imdb.com/images/M/MV5BMTQ3Mjg2...,The Kadam family leaves India for France where...,"The family of talented cook, Hassan Kadam, has...","english, french, hindi","india, united arab emirates, usa",nominated for 1 golden globe. another 2 wins &...,2015-11-19 00:01:11.080000000
2,31,102 dalmatians,bv,66957026,2704,19883351,2704,2000-11-22,2000,102 dalmatians|2000,...,35,4.8,24690,http://ia.media-imdb.com/images/M/MV5BMTY1NjMw...,Cruella DeVil gets out of prison and goes afte...,After a spot of therapy Cruella De Vil is rele...,english,"usa, uk",nominated for 1 oscar. another 1 win & 2 nomin...,2015-11-11 01:07:04.023000000
3,12,10 days in a madhouse,cafep,14616,10,4773,1,2015-11-11,2015,10 days in a madhouse|2015,...,NaN,NaN,NaN,http://ia.media-imdb.com/images/M/MV5BOTI3MDU4...,"In 1887, at age 23, reporter Nellie Bly, worki...","In 1887, at age 23, reporter Nellie Bly, worki...",english,usa,NaN,2015-11-04 00:21:03.970000000
4,13,10 items or less,think,83291,15,35929,15,2006-12-01,2006,10 items or less|2006,...,54,6.7,12426,http://ia.media-imdb.com/images/M/MV5BMTI1MTU4...,An actor (Freeman) prepping for an upcoming ro...,"A well-known actor, who hasn't accepted a role...","english, spanish",usa,1 win & 1 nomination.,2015-11-07 00:24:07.743000000
5,32,10th and wolf,think,54702,6,20774,6,2006-08-18,2006,10th and wolf|2006,...,36,6.4,5458,http://ia.media-imdb.com/images/M/MV5BMjE1NDE0...,A former street tough returns to his Philadelp...,"February, 1991. Tommy, a Desert Storm marine d...","english, italian",usa,NaN,2015-11-14 00:13:47.697000000
6,16,10 things i hate about you,bv,38178166,2311,8330681,2271,1999-03-31,1999,10 things i hate about you|1999,...,70,7.2,205054,http://ia.media-imdb.com/images/M/MV5BMTI4MzU5...,A new kid must find a guy to date the meanest ...,"Adapted from William Shakespeare's play ""The T...","english, french",usa,2 wins & 13 nominations.,2015-11-06 01:09:03.317000000
7,17,10 to midnight,mgm,7175592,595,3050225,595,1983-03-11,1983,10 to midnight|1983,...,NaN,6.2,4046,http://ia.media-imdb.com/images/M/MV5BMTc3NzY4...,A LAPD detective is on the trail of a very han...,"In Los Angeles, the rookie Detective Paul McAn...",english,usa,NaN,2015-11-03 00:26:31.427000000
8,35,the 11th hour,wip,707343,111,60853,4,2007-08-17,2007,the 11th hour|2007,...,63,7.3,4718,http://ia.media-imdb.com/images/M/MV5BMTc3MjE1...,A look at the state of the global environment ...,A look at the state of the global environment ...,english,usa,3 nominations.,2015-11-13 01:50:49.377000000
9,35,the 11th hour,wip,707343,111,60853,4,2007-08-17,2007,the 11th hour|2007,...,NaN,7.5,15,NaN,"A family drama set in Addis, revolves around a...","A family drama set in Addis, revolves around a...",amharic,ethiopia,NaN,2015-09-14 07:21:15.987000000
10,37,12,spc,125120,20,12042,5,2009-03-04,2009,12|2009,...,NaN,7.5,6,NaN,There comes a time when every hall monitor mus...,There comes a time when every hall monitor mus...,english,usa,NaN,2015-11-20 00:46:19.853000000
11,37,12,spc,125120,20,12042,5,2009-03-04,2009,12|2009,...,NaN,NaN,NaN,NaN,"After blowing his professional ballet career, ...","After blowing his professional ballet career, ...",english,usa,NaN,2015-03-28 01:06:43.987000000
12,44,127 hours,foxs,18335230,916,264851,4,2010-11-05,2010,127 hours|2010,...,82,7.6,260232,http://ia.media-imdb.com/images/M/MV5BMTc2NjMz...,An adventurous mountain climber becomes trappe...,127 Hours is the true story of mountain climbe...,"english, italian","usa, uk",nominated for 6 oscars. another 22 wins & 135 ...,2015-11-03 00:22:16.057000000
13,41,12 rounds,fox,12234694,2331,5329240,2331,2009-03-27,2009,12 rounds|2009,...,38,5.6,21705,http://ia.media-imdb.com/images/M/MV5BMTU1MzM1...,Detective Danny Fisher discovers his girlfrien...,Uniformed New Orleans PD officer Danny Fisher ...,english,usa,NaN,2015-11-04 00:16:32.620000000
14,48,13 going on 30,sonr,57231747,3453,21054283,3438,2004-04-23,2004,13 going on 30|2004,...,57,6.1,112192,http://ia.media-imdb.com/images/M/MV5BMjA1MTI3...,A 13 year old girl plays a game on her 13th bi...,After total humiliation at her thirteenth birt...,"english, portuguese",usa,11 nominations.,2015-11-06 01:49:52.520000000
15,49,13 hours: the secret soldiers of benghazi,par.,NaN,NaN,NaN,NaN,2016-01-15,2016,13 hours: the secret soldiers of benghazi|2016,...,NaN,NaN,NaN,http://ia.media-imdb.com/images/M/MV5BMjU3OTQ5...,An American Ambassador is killed during an att...,An American Ambassador is killed during an att...,english,usa,NaN,2015-11-19 00:53:23.163000000
16,51,13 sins,rtwc,13809,45,9261,45,2014-04-18,2014,13 sins|2014,...,44,6.3,20566,http://ia.media-imdb.com/images/M/MV5BNzA0NDIw...,A cryptic phone call sets off a dangerous game...,"Elliot Brindle is a bright, meek salesman, dro...",english,usa,2 nominations.,2015-11-06 00:12:04.113000000
17,54,the 13th alley,schf.,250992,72,112946,72,2008-06-13,2008,the 13th alley|2008,...,NaN,6.2,56,NaN,A group of college kids go after-hours bowling...,A group of college kids go after-hours bowling...,english,usa,NaN,2015-03-15 01:19:47.790000000
18,55,the 13th warrior,bv,32698899,2313,10267756,2306,1999-08-27,1999,the 13th warrior|1999,...,42,6.6,98032,http://ia.media-imdb.com/images/M/MV5BMTcxNTUx...,"A man, having fallen in love with the wrong wo...","In AD 922, Arab courtier Ahmad Ibn Fadlan acco...","english, latin, swedish, norse, old, danish",usa,2 wins & 2 nominations.,2015-11-04 00:01:14.663000000
19,57,1408,mgm/w,71985628,2733,20617667,2678,2007-06-22,2007,1408|2007,...,64,6.8,198518,http://ia.media-imdb.com/images/M/MV5BMTk1MDg0...,A man who specializes in debunking paranormal ...,The cynical and skeptical writer Mike Enslin w...,english,usa,4 wins & 8 nominations.,2015-11-04 01:04:11.810000000
20,58,1492: conquest of paradise,par.,7191399,1008,3002680,1008,1992-10-09,1992,1492: conquest of paradise|1992,...,NaN,6.5,21527,http://ia.media-imdb.com/images/M/MV5BMTIyNzQ3...,Christopher Columbus' discovery of the America...,Big budget account of Christopher Columbus' di...,english,"france, spain",nominated for 1 golden globe. another 1 nomina...,2015-12-01 03:30:48.613000000
21,59,15,pict.,3013,1,633,1,2005-04-13,2005,15|2005,...,NaN,5.8,672,NaN,NaN,NaN,"romanian, french",romania,1 win.,2015-11-13 04:12:52.300000000
22,61,15 minutes,nl,24403552,2337,10523154,2337,2001-03-09,2001,15 minutes|2001,...,34,6.1,41195,http://ia.media-imdb.com/images/M/MV5BMTI3MzQ1...,A homicide detective and a fire marshall must ...,When Eastern European criminals Oleg and Emil ...,"english, czech, russian, greek, afrikaans","usa, germany",1 nomination.,2015-11-29 01:55:52.113000000
23,61,15 minutes,nl,24403552,2337,10523154,2337,2001-03-09,2001,15 minutes|2001,...,34,6.1,41004,http://ia.media-imdb.com/images/M/MV5BMTI3MzQ1...,A homicide detective and a fire marshall must ...,When Eastern European criminals Oleg and Emil ...,"english, czech, russian, greek, afrikaans","usa, germany",1 nomination.,2015-10-20 00:04:27.773000000
24,62,16 blocks,wb,36895141,2706,11855260,2706,2006-03-03,2006,16 blocks|2006,...,63,6.6,109171,http://ia.media-imdb.com/images/M/MV5BMTQ1NDEw...,An aging alcoholic cop is assigned the task of...,"Jack Mosley, a burnt-out detective, is assigne...",english,"germany, usa",1 nomination.,2015-11-07 00:47:48.317000000
25,63,16 days of glory,par.,83857,NaN,NaN,NaN,1986-03-07,1986,16 days of glory|1986,...,NaN,7.7,90,http://ia.media-imdb.com/images/M/MV5BMjI1Nzcy...,The definitive photographic record of the 1984...,The definitive photographic record of the 1984...,english,usa,1 win.,2014-12-29 00:04:17.080000000
26,65,17 again,wb (nl),64167069,3255,23722310,3255,2009-04-17,2009,17 again|2009,...,48,6.4,137303,http://ia.media-imdb.com/images/M/MV5BMjA2NTI1...,About a guy whose life didn't quite turn out h...,NaN,english,usa,3 wins & 4 nominations.,2015-11-15 03:39:19.207000000
27,72,1911,vari.,135739,33,55850,33,2011-10-07,2011,1911|2011,...,37,6.0,4510,http://ia.media-imdb.com/images/M/MV5BMTM3OTQw...,A historical drama based on the founding of th...,A historical drama based on the founding of th...,"mandarin, english, french","china, hong kong",4 wins & 7 nominations.,2015-11-18 04:14:08.087000000
28,73,1915,bm,96682,10,30448,8,2015-04-17,2015,1915|2015,...,NaN,4.2,931,http://ia.media-imdb.com/images/M/MV5BNTMxNDcz...,"Exactly 100 years after the Armenian Genocide,...","In 2015, exactly 100 years after the Armenian ...",english,usa,NaN,2015-11-25 01:00:37.077000000
29,14507,tomorrowland,bv,93436322,3972,33028165,3972,2015-05-22,2015,tomorrowland|2015,...,60,6.5,89070,http://ia.media-imdb.com/images/M/MV5BMTQ0MDc5...,"Bound by a shared destiny, a teen bursting wit...","Bound by a shared destiny, a bright, optimisti...","english, french, japanese","usa, spain",3 nominations.,2015-11-19 00:13:42.117000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9125,15073,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9126,15073,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9127,15098,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9128,15098,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9129,15188,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9130,15188,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9131,15251,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9132,15251,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9133,15269,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9134,15269,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9135,15445,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9136,15445,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9137,15537,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9138,15537,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9139,15723,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9140,15723,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9141,15875,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9142,15875,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9143,15963,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9144,15963,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9145,15987,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9146,15987,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9147,16006,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9148,16006,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9149,16121,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9150,16121,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9151,16127,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9152,16127,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9153,16179,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9154,16179,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
box_omdb[box_omdb.btitle == 'kate and leopold']

,list_number,btitle,studio,total_gross,total_theatres,opening_gross,opening_theatres,opening_date,byear,title_year,...,metacritic,imdbrating,imdbvotes,poster,plot,fullplot,language,country,awards,lastupdated
4263,7732,kate and leopold,mira.,47121859,2467,9725408,2452,2001-12-25,2001,kate and leopold|2001,...,44,6.3,61093,http://ia.media-imdb.com/images/M/MV5BODU1MzU0...,Kate and her actor brother live in N.Y. in the...,Kate and her actor brother live in N.Y. in the...,"english, french",usa,nominated for 1 oscar. another 1 win & 4 nomin...,2015-12-03 00:58:15.250000000

In [24]:
box_omdb[box_omdb.byear >= '2000']

,list_number,btitle,studio,total_gross,total_theatres,opening_gross,opening_theatres,opening_date,byear,title_year,...,metacritic,imdbrating,imdbvotes,poster,plot,fullplot,language,country,awards,lastupdated
0,385,after earth,sony,60522097,3401,27520040,3401,2013-05-31,2013,after earth|2013,...,33,4.9,150066,http://ia.media-imdb.com/images/M/MV5BMTY3MzQy...,A crash landing leaves Kitai Raige and his fat...,One thousand years after cataclysmic events fo...,english,usa,3 wins & 7 nominations.,2015-11-24 00:18:05.520000000
1,6817,the hundred-foot journey,bv,54240821,2167,10979290,2023,2014-08-08,2014,the hundred-foot journey|2014,...,55,7.3,44661,http://ia.media-imdb.com/images/M/MV5BMTQ3Mjg2...,The Kadam family leaves India for France where...,"The family of talented cook, Hassan Kadam, has...","english, french, hindi","india, united arab emirates, usa",nominated for 1 golden globe. another 2 wins &...,2015-11-19 00:01:11.080000000
2,31,102 dalmatians,bv,66957026,2704,19883351,2704,2000-11-22,2000,102 dalmatians|2000,...,35,4.8,24690,http://ia.media-imdb.com/images/M/MV5BMTY1NjMw...,Cruella DeVil gets out of prison and goes afte...,After a spot of therapy Cruella De Vil is rele...,english,"usa, uk",nominated for 1 oscar. another 1 win & 2 nomin...,2015-11-11 01:07:04.023000000
3,12,10 days in a madhouse,cafep,14616,10,4773,1,2015-11-11,2015,10 days in a madhouse|2015,...,NaN,NaN,NaN,http://ia.media-imdb.com/images/M/MV5BOTI3MDU4...,"In 1887, at age 23, reporter Nellie Bly, worki...","In 1887, at age 23, reporter Nellie Bly, worki...",english,usa,NaN,2015-11-04 00:21:03.970000000
4,13,10 items or less,think,83291,15,35929,15,2006-12-01,2006,10 items or less|2006,...,54,6.7,12426,http://ia.media-imdb.com/images/M/MV5BMTI1MTU4...,An actor (Freeman) prepping for an upcoming ro...,"A well-known actor, who hasn't accepted a role...","english, spanish",usa,1 win & 1 nomination.,2015-11-07 00:24:07.743000000
5,32,10th and wolf,think,54702,6,20774,6,2006-08-18,2006,10th and wolf|2006,...,36,6.4,5458,http://ia.media-imdb.com/images/M/MV5BMjE1NDE0...,A former street tough returns to his Philadelp...,"February, 1991. Tommy, a Desert Storm marine d...","english, italian",usa,NaN,2015-11-14 00:13:47.697000000
8,35,the 11th hour,wip,707343,111,60853,4,2007-08-17,2007,the 11th hour|2007,...,63,7.3,4718,http://ia.media-imdb.com/images/M/MV5BMTc3MjE1...,A look at the state of the global environment ...,A look at the state of the global environment ...,english,usa,3 nominations.,2015-11-13 01:50:49.377000000
9,35,the 11th hour,wip,707343,111,60853,4,2007-08-17,2007,the 11th hour|2007,...,NaN,7.5,15,NaN,"A family drama set in Addis, revolves around a...","A family drama set in Addis, revolves around a...",amharic,ethiopia,NaN,2015-09-14 07:21:15.987000000
10,37,12,spc,125120,20,12042,5,2009-03-04,2009,12|2009,...,NaN,7.5,6,NaN,There comes a time when every hall monitor mus...,There comes a time when every hall monitor mus...,english,usa,NaN,2015-11-20 00:46:19.853000000
11,37,12,spc,125120,20,12042,5,2009-03-04,2009,12|2009,...,NaN,NaN,NaN,NaN,"After blowing his professional ballet career, ...","After blowing his professional ballet career, ...",english,usa,NaN,2015-03-28 01:06:43.987000000
12,44,127 hours,foxs,18335230,916,264851,4,2010-11-05,2010,127 hours|2010,...,82,7.6,260232,http://ia.media-imdb.com/images/M/MV5BMTc2NjMz...,An adventurous mountain climber becomes trappe...,127 Hours is the true story of mountain climbe...,"english, italian","usa, uk",nominated for 6 oscars. another 22 wins & 135 ...,2015-11-03 00:22:16.057000000
13,41,12 rounds,fox,12234694,2331,5329240,2331,2009-03-27,2009,12 rounds|2009,...,38,5.6,21705,http://ia.media-imdb.com/images/M/MV5BMTU1MzM1...,Detective Danny Fisher discovers his girlfrien...,Uniformed New Orleans PD officer Danny Fisher ...,english,usa,NaN,2015-11-04 00:16:32.620000000
14,48,13 going on 30,sonr,57231747,3453,21054283,3438,2004-04-23,2004,13 going on 30|2004,...,57,6.1,112192,http://ia.media-imdb.com/images/M/MV5BMjA1MTI3...,A 13 year old girl plays a game on her 13th bi...,After total humiliation at her thirteenth birt...,"english, portuguese",usa,11 nominations.,2015-11-06 01:49:52.520000000
15,49,13 hours: the secret soldiers of benghazi,par.,NaN,NaN,NaN,NaN,2016-01-15,2016,13 hours: the secret soldiers of benghazi|2016,...,NaN,NaN,NaN,http://ia.media-imdb.com/images/M/MV5BMjU3OTQ5...,An American Ambassador is killed during an att...,An American Ambassador is killed during an att...,english,usa,NaN,2015-11-19 00:53:23.163000000
16,51,13 sins,rtwc,13809,45,9261,45,2014-04-18,2014,13 sins|2014,...,44,6.3,20566,http://ia.media-imdb.com/images/M/MV5BNzA0NDIw...,A cryptic phone call sets off a dangerous game...,"Elliot Brindle is a bright, meek salesman, dro...",english,usa,2 nominations.,2015-11-06 00:12:04.113000000
17,54,the 13th alley,schf.,250992,72,112946,72,2008-06-13,2008,the 13th alley|2008,...,NaN,6.2,56,NaN,A group of college kids go after-hours bowling...,A group of college kids go after-hours bowling...,english,usa,NaN,2015-03-15 01:19:47.790000000
19,57,1408,mgm/w,71985628,2733,20617667,2678,2007-06-22,2007,1408|2007,...,64,6.8,198518,http://ia.media-imdb.com/images/M/MV5BMTk1MDg0...,A man who specializes in debunking paranormal ...,The cynical and skeptical writer Mike Enslin w...,english,usa,4 wins & 8 nominations.,2015-11-04 01:04:11.810000000
21,59,15,pict.,3013,1,633,1,2005-04-13,2005,15|2005,...,NaN,5.8,672,NaN,NaN,NaN,"romanian, french",romania,1 win.,2015-11-13 04:12:52.300000000
22,61,15 minutes,nl,24403552,2337,10523154,2337,2001-03-09,2001,15 minutes|2001,...,34,6.1,41195,http://ia.media-imdb.com/images/M/MV5BMTI3MzQ1...,A homicide detective and a fire marshall must ...,When Eastern European criminals Oleg and Emil ...,"english, czech, russian, greek, afrikaans","usa, germany",1 nomination.,2015-11-29 01:55:52.113000000
23,61,15 minutes,nl,24403552,2337,10523154,2337,2001-03-09,2001,15 minutes|2001,...,34,6.1,41004,http://ia.media-imdb.com/images/M/MV5BMTI3MzQ1...,A homicide detective and a fire marshall must ...,When Eastern European criminals Oleg and Emil ...,"english, czech, russian, greek, afrikaans","usa, germany",1 nomination.,2015-10-20 00:04:27.773000000
24,62,16 blocks,wb,36895141,2706,11855260,2706,2006-03-03,2006,16 blocks|2006,...,63,6.6,109171,http://ia.media-imdb.com/images/M/MV5BMTQ1NDEw...,An aging alcoholic cop is assigned the task of...,"Jack Mosley, a burnt-out detective, is assigne...",english,"germany, usa",1 nomination.,2015-11-07 00:47:48.317000000
26,65,17 again,wb (nl),64167069,3255,23722310,3255,2009-04-17,2009,17 again|2009,...,48,6.4,137303,http://ia.media-imdb.com/images/M/MV5BMjA2NTI1...,About a guy whose life didn't quite turn out h...,NaN,english,usa,3 wins & 4 nominations.,2015-11-15 03:39:19.207000000
27,72,1911,vari.,135739,33,55850,33,2011-10-07,2011,1911|2011,...,37,6.0,4510,http://ia.media-imdb.com/images/M/MV5BMTM3OTQw...,A historical drama based on the founding of th...,A historical drama based on the founding of th...,"mandarin, english, french","china, hong kong",4 wins & 7 nominations.,2015-11-18 04:14:08.087000000
28,73,1915,bm,96682,10,30448,8,2015-04-17,2015,1915|2015,...,NaN,4.2,931,http://ia.media-imdb.com/images/M/MV5BNTMxNDcz...,"Exactly 100 years after the Armenian Genocide,...","In 2015, exactly 100 years after the Armenian ...",english,usa,NaN,2015-11-25 01:00:37.077000000
29,14507,tomorrowland,bv,93436322,3972,33028165,3972,2015-05-22,2015,tomorrowland|2015,...,60,6.5,89070,http://ia.media-imdb.com/images/M/MV5BMTQ0MDc5...,"Bound by a shared destiny, a teen bursting wit...","Bound by a shared destiny, a bright, optimisti...","english, french, japanese","usa, spain",3 nominations.,2015-11-19 00:13:42.117000000
33,106,2012,sony,166112167,3444,65237614,3404,2009-11-13,2009,2012|2009,...,49,5.8,266145,http://ia.media-imdb.com/images/M/MV5BMTY0MjEy...,A frustrated writer struggles to keep his fami...,"Dr. Adrian Helmsley, part of a worldwide geoph...","english, french, tibetan, mandarin, russian, h...",usa,4 wins & 20 nominations.,2015-12-03 05:02:39.047000000
34,106,2012,sony,166112167,3444,65237614,3404,2009-11-13,2009,2012|2009,...,NaN,5.2,175,NaN,NaN,NaN,german,germany,1 nomination.,2015-10-08 05:08:03.980000000
35,108,2012: time for change,mang.,68339,2,9009,1,2010-04-09,2010,2012: time for change|2010,...,NaN,7.2,307,http://ia.media-imdb.com/images/M/MV5BMTQ4MTUw...,2012: Time For Change is a documentary feature...,2012: Time For Change is a documentary feature...,english,"usa, brazil, france, mexico, switzerland",1 nomination.,2015-11-22 03:09:01.097000000
36,114,21,sony,81159365,2952,24105943,2648,2008-03-28,2008,21|2008,...,48,6.8,182895,http://ia.media-imdb.com/images/M/MV5BMjAyNTU5...,21 is the fact-based story about six MIT stude...,"Ben Campbell is a young, highly intelligent, s...",english,usa,1 win & 5 nominations.,2015-11-05 05:47:08.733000000
37,115,21 and over,rela.,25682380,2771,8754168,2771,2013-03-01,2013,21 and over|2013,...,34,5.9,56758,http://ia.media-imdb.com/images/M/MV5BMjI0NTEx...,The night before his big medical school interv...,When Straight-A college student Jeff Chang's t...,"english, spanish",usa,1 win & 1 nomination.,2015-11-06 01:46:19.313000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9125,15073,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9126,15073,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9127,15098,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9128,15098,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9129,15188,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9130,15188,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9131,15251,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9132,15251,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9133,15269,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9134,15269,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9135,15445,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9136,15445,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9137,15537,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9138,15537,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9139,15723,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9140,15723,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9141,15875,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9142,15875,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9143,15963,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9144,15963,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9145,15987,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9146,15987,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9147,16006,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9148,16006,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9149,16121,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9150,16121,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9151,16127,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9152,16127,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9153,16179,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9154,16179,NaN,studio,NaN,NaN,NaN,NaN,NaT,nan,NaN,...,2015-10-22 12:45:02.117000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
box_omdb.byear.value_counts()

2015    466
2013    459
2014    447
2012    436
2011    368
2008    351
2006    347
2007    346
2009    330
2010    310
2005    308
2004    303
nan     288
2002    262
2003    255
2000    241
1999    241
1996    221
1998    216
2001    213
1995    212
1997    210
1988    196
1993    193
1994    188
1987    183
1991    178
1992    177
1989    174
1990    173
1986    162
1985    150
1984    137
2016    125
1983    115
1982    106
2017     41
2018     17
2019      8
2020      2
Name: byear, dtype: int64

In [26]:
# read in the rotten tomatoes file
tomatoes = pd.read_csv('./tomatoes.txt', delimiter='\t', error_bad_lines = False)
tomatoes.head()

,ID,Image,Rating,Meter,Reviews,Fresh,Rotten,Consensus,userMeter,userRating,userReviews,DVD,BoxOffice,Production,Website,lastUpdated
0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100,2.8,216,NaN,NaN,NaN,NaN,2015-10-27 08:48:11.737000000
1,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32,3.0,184,NaN,NaN,NaN,NaN,2015-10-11 17:01:44.983000000
2,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.7,129,NaN,NaN,NaN,NaN,2015-10-27 08:48:23.970000000
3,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.7,60,NaN,NaN,NaN,NaN,2015-11-12 12:31:48.700000000
4,89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.9,51,NaN,NaN,NaN,NaN,2015-11-03 17:51:29.713000000

In [27]:
# normalize column names and make production column lowercaseand convert id column into numeric in order to merge OMDB and Tomatoes dataframes
tomatoes.columns = map(str.lower, tomatoes.columns)
tomatoes.rename(columns = {'lastupdated':'tlastupdated', 'rating':'trating'}, inplace = True)
tomatoes.production = tomatoes.production.str.lower()
omdb.id = omdb.id.convert_objects(convert_numeric=True)
omdb_tomatoes = pd.merge(omdb, tomatoes, on = 'id', how = 'inner')
omdb_tomatoes

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:5: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.

,id,imdbid,otitle,oyear,rating,runtime,genre,released,director,writer,...,rotten,consensus,usermeter,userrating,userreviews,dvd,boxoffice,production,website,tlastupdated
0,4,tt0000004,un bon bock,1892,NaN,NaN,"animation, short",1892-10-28,Émile reynaud,NaN,...,NaN,NaN,100,2.8,216,NaN,NaN,NaN,NaN,2015-10-27 08:48:11.737000000
1,5,tt0000005,blacksmith scene,1893,unrated,1 min,short,1893-05-09,william k.l. dickson,NaN,...,NaN,NaN,32,3.0,184,NaN,NaN,NaN,NaN,2015-10-11 17:01:44.983000000
2,10,tt0000010,employees leaving the lumière factory,1895,NaN,1 min,"documentary, short",1895-03-22,louis lumière,NaN,...,NaN,NaN,NaN,3.7,129,NaN,NaN,NaN,NaN,2015-10-27 08:48:23.970000000
3,75,tt0000075,the conjuring of a woman at the house of rober...,1896,NaN,1 min,short,NaN,georges méliès,NaN,...,NaN,NaN,NaN,3.7,60,NaN,NaN,NaN,NaN,2015-11-12 12:31:48.700000000
4,89,tt0000089,leaving jerusalem by railway,1897,NaN,1 min,"documentary, short",NaN,alexandre promio,NaN,...,NaN,NaN,NaN,3.9,51,NaN,NaN,NaN,NaN,2015-11-03 17:51:29.713000000
5,174,tt0000174,výstavní párkar a lepic plakátù,1898,NaN,1 min,"short, comedy",1898-07-01,jan krízenecký,josef sváb-malostranský (story),...,NaN,NaN,NaN,5.0,23,NaN,NaN,NaN,NaN,2015-10-27 08:53:30.047000000
6,211,tt0000211,a trip to the moon,1898,NaN,3 min,"short, fantasy",NaN,georges méliès,georges méliès (creator),...,NaN,NaN,NaN,4.0,47,NaN,NaN,NaN,NaN,2015-10-26 11:39:11.820000000
7,230,tt0000230,cinderella,1899,NaN,6 min,"drama, short",1899-12-25,georges méliès,charles perrault (story),...,NaN,NaN,NaN,3.7,80,NaN,NaN,NaN,NaN,2015-10-26 01:15:33.437000000
8,242,tt0000242,the sign of the cross,1899,NaN,3 min,"short, fantasy",1900-06-30,georges méliès,georges méliès,...,NaN,NaN,NaN,3.4,33,NaN,NaN,NaN,NaN,2015-10-12 17:51:30.280000000
9,309,tt0000309,how it feels to be run over,1900,not rated,1 min,short,1900-07-01,cecil m. hepworth,NaN,...,NaN,NaN,NaN,3.8,32,NaN,NaN,NaN,NaN,2015-10-12 17:51:57.020000000
10,357,tt0000357,the haunted curiosity shop,1901,NaN,NaN,"short, comedy, fantasy",1902-05-01,walter r. booth,NaN,...,NaN,NaN,25,3.6,45,NaN,NaN,NaN,NaN,2015-11-03 04:21:41.617000000
11,359,tt0000359,the india rubber head,1901,NaN,3 min,"short, comedy",NaN,georges méliès,NaN,...,NaN,NaN,NaN,3.9,98,NaN,NaN,NaN,NaN,2015-11-12 16:53:19.013000000
12,417,tt0000417,a trip to the moon,1902,tv-g,13 min,"short, adventure, fantasy",1902-10-04,georges méliès,NaN,...,0,NaN,90,4.2,6559,NaN,NaN,NaN,NaN,2015-10-25 18:52:04.237000000
13,420,tt0000420,alice in wonderland,1903,NaN,8 min,"fantasy, short",1903-10-17,"cecil m. hepworth, percy stow","lewis carroll (novel), cecil m. hepworth",...,NaN,NaN,47,3.2,375,NaN,NaN,NaN,NaN,2015-10-26 05:20:17.923000000
14,439,tt0000439,the great train robbery,1903,tv-g,11 min,"short, western",1903-12-01,edwin s. porter,NaN,...,0,NaN,75,3.7,2574,2003-12-16,NaN,NaN,NaN,2015-10-29 15:16:01.930000000
15,447,tt0000447,life of an american fireman,1903,not rated,6 min,"short, action",1903-01-01,"george s. fleming, edwin s. porter",NaN,...,NaN,NaN,NaN,3.6,87,NaN,NaN,NaN,NaN,2015-10-27 09:02:07.510000000
16,455,tt0000455,the music lover,1903,NaN,3 min,"short, comedy, music",1903-08-15,georges méliès,NaN,...,NaN,NaN,78,3.8,73,NaN,NaN,NaN,NaN,2015-10-12 17:52:59.897000000
17,488,tt0000488,the land beyond the sunset,1912,unrated,14 min,"short, drama, fantasy",1912-10-28,harold m. shaw,dorothy g. shore,...,NaN,NaN,71,3.7,54,NaN,NaN,NaN,NaN,2015-10-12 17:53:12.587000000
18,498,tt0000498,rescued by rover,1905,NaN,7 min,"short, drama, family",1905-08-19,"lewin fitzhamon, cecil m. hepworth",mrs. hepworth (story),...,NaN,NaN,94,3.9,75,NaN,NaN,NaN,NaN,2015-10-12 17:53:18.150000000
19,499,tt0000499,the voyage across the impossible,1904,NaN,24 min,"short, adventure, fantasy",1904-10-01,georges méliès,"georges méliès, jules verne (play), adolphe d'...",...,NaN,NaN,93,4.1,311,NaN,NaN,NaN,NaN,2015-10-05 18:49:34.093000000
20,516,tt0000516,the electric hotel,1908,NaN,8 min,"animation, short",1908-12-19,segundo de chomón,NaN,...,NaN,NaN,NaN,2.8,3,NaN,NaN,NaN,NaN,2015-11-03 08:22:30.973000000
21,524,tt0000524,new york subway,1905,unrated,6 min,"short, documentary",1905-06-05,g.w. bitzer,NaN,...,NaN,NaN,40,3.1,59,NaN,NaN,NaN,NaN,2015-10-12 17:53:29.590000000
22,546,tt0000546,dream of a rarebit fiend,1906,NaN,7 min,"short, fantasy",1906-02-01,"wallace mccutcheon, edwin s. porter",winsor mccay (comic strip),...,NaN,NaN,64,3.6,64,NaN,NaN,NaN,NaN,2015-10-12 17:53:43.687000000
23,574,tt0000574,the story of the kelly gang,1906,NaN,70 min,"biography, crime, drama",1906-12-26,charles tait,charles tait,...,NaN,NaN,NaN,3.5,2,NaN,NaN,NaN,NaN,2015-11-12 06:52:40
24,614,tt0000614,the red spectre,1907,NaN,9 min,"short, fantasy",1907-08-17,"segundo de chomón, ferdinand zecca",segundo de chomón,...,NaN,NaN,60,3.7,36,NaN,NaN,NaN,NaN,2015-11-02 13:37:11.123000000
25,755,tt0000755,the dream of an opium fiend,1908,NaN,4 min,short,1908-03-01,georges méliès,NaN,...,NaN,NaN,NaN,2.5,3,NaN,NaN,NaN,NaN,2015-10-12 17:55:12.283000000
26,785,tt0000785,where the breakers roar,1908,NaN,9 min,"drama, short",1908-09-22,d.w. griffith,"d.w. griffith, stanner e.v. taylor",...,NaN,NaN,NaN,0.0,40,NaN,NaN,NaN,NaN,2015-10-12 17:55:24.733000000
27,832,tt0000832,a corner in wheat,1909,g,14 min,"short, drama",1909-12-13,d.w. griffith,NaN,...,NaN,NaN,71,3.6,112,NaN,NaN,NaN,NaN,2015-10-27 09:14:20.003000000
28,854,tt0000854,edgar allan poe,1909,NaN,NaN,"short, biography",1909-02-08,d.w. griffith,"d.w. griffith, frank e. woods",...,NaN,NaN,100,3.8,13,NaN,NaN,NaN,NaN,2015-10-27 09:15:03.100000000
29,924,tt0000924,a bad case,1909,NaN,NaN,"animation, short",1909-07-10,Émile cohl,NaN,...,NaN,NaN,NaN,4.0,31,NaN,NaN,NaN,NaN,2015-10-27 09:17:21.550000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94993,4707756,tt4707756,the world is mine,2015,NaN,104 min,drama,2015-06-05,nicolae constantin tanase,raluca manescu,...,NaN,NaN,NaN,4.5,1,NaN,NaN,NaN,NaN,2015-10-28 02:28:31.347000000
94994,4724214,tt4724214,america's first d-day: washington's crossing,2014,NaN,47 min,action,2014-12-04,robert child,robert child,...,NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,2015-10-25 15:57:28.673000000
94995,4725816,tt4725816,el espejo del arte,2014,NaN,NaN,documentary,NaN,pablo jato,pablo jato,...,NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,2015-11-11 22:35:03.817000000
94996,4727512,tt4727512,srimanthudu,2015,NaN,158 min,"action, drama",2015-08-07,koratalla siva,koratalla siva,...,NaN,NaN,NaN,3.6,52,NaN,NaN,NaN,NaN,2015-11-09 13:56:39.747000000
94997,4727756,tt4727756,the ark of mr chow,2015,NaN,106 min,comedy,2015-06-19,yang xiao,"xiao yang, ji zhang",...,NaN,NaN,33,3.2,67,NaN,$53.3k,china lion entertainment,http://www.TheArkOfMrChow.com/,2015-10-25 17:30:29.037000000
94998,4746370,tt4746370,death of a gentleman,2015,NaN,99 min,documentary,2015-06-08,"johnny blank, sam collins, jarrod kimber","sam collins, jon hotten, jarrod kimber",...,NaN,NaN,NaN,0.0,25,NaN,NaN,NaN,NaN,2015-10-26 00:37:10.727000000
94999,4756812,tt4756812,the kliq rules,2015,NaN,NaN,"documentary, sport",2015-07-28,NaN,NaN,...,NaN,NaN,NaN,0.0,0,2015-07-28,NaN,warner brothers pictures,NaN,2015-11-14 18:36:55.070000000
95000,4759196,tt4759196,the seventh dwarf,2014,pg,87 min,"animation, adventure, comedy",2015-07-31,"boris aljinovic, harald siepermann","harald siepermann (screenplay), douglas welbat...",...,7,NaN,31,2.2,83,2015-08-18,NaN,shout! factory,http://www.seventhdwarfmovie.com,2015-10-16 19:41:20.967000000
95001,4759240,tt4759240,message from hiroshima,2015,NaN,53 min,documentary,2015-08-04,masaaki tanabe,masaaki tanabe,...,NaN,NaN,NaN,3.0,1,NaN,NaN,NaN,NaN,2015-10-26 02:09:57.867000000
95002,4762826,tt4762826,innimey ippadithaan,2015,NaN,134 min,"comedy, romance",2015-06-12,muruganand,muruganand,...,NaN,NaN,NaN,3.5,1,NaN,NaN,NaN,NaN,2015-11-03 02:00:50.727000000
95003,4764370,tt4764370,"guillaume, la jeunesse du conquérant",2015,NaN,90 min,NaN,2015-05-06,fabien drugeon,fabien drugeon (screenplay),...,NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,2015-08-10 18:19:47.593000000
95004,4772750,tt4772750,ego trip,2015,NaN,105 min,comedy,2015-07-08,benoit pelletier,françois avard,...,NaN,NaN,NaN,2.8,19,NaN,NaN,NaN,NaN,2015-10-31 07:50:17.630000000
95005,4777072,tt4777072,blue like me: the art of siona benjamin,2015,NaN,28 min,"documentary, biography, history",2015-05-01,hal rifken,"ryan arey (story), ryan arey, hal rifken (story)",...,NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,2015-11-04 04:15:31.300000000
95006,4788638,tt4788638,to the fore,2015,NaN,125 min,"drama, sport",2015-08-07,dante lam,"silver hau (screenplay), dante lam (screenplay...",...,NaN,NaN,70,3.6,47,NaN,NaN,asia releasing,http://www.totheforemovie.com,2015-10-06 17:40:38.007000000
95007,4789202,tt4789202,my boy,2015,NaN,96 min,NaN,2015-04-01,giorgio serafini,"ladon drummond, giorgio serafini",...,NaN,NaN,0,2.5,1,2015-03-24,NaN,NaN,NaN,2015-10-15 18:36:10.573000000
95008,4818250,tt4818250,jian bing man,2015,NaN,113 min,comedy,2015-07-24,chengpeng dong,NaN,...,NaN,NaN,65,3.5,159,NaN,NaN,asia releasing,http://www.jianbingmanmovie.com/,2015-10-25 17:25:31.600000000
95009,4843592,tt4843592,late expectations,2015,NaN,12 min,"short, drama, romance",NaN,laurie arakaki,thais francis,...,NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,2015-11-09 20:45:44.627000000
95010,4844288,tt4844288,the treacherous,2015,NaN,133 min,history,2015-05-21,kyu-dong min,NaN,...,NaN,NaN,NaN,3.2,5,NaN,NaN,NaN,NaN,2015-10-26 03:36:44.390000000
95011,4847012,tt4847012,uranium: twisting the dragon's tail,2015,NaN,NaN,documentary,2015-07-29,wain fimeri,"wain fimeri, steve westh (additional writer)",...,NaN,NaN,NaN,5.0,1,NaN,NaN,NaN,NaN,2015-10-28 14:48:27.080000000
95012,4861730,tt4861730,the reflektor tapes,2015,NaN,75 min,"documentary, music",2015-09-24,kahlil joseph,NaN,...,9,NaN,63,3.3,119,NaN,NaN,arts alliance,http://www.thereflektortapes.com/,2015-10-16 17:35:23.483000000
95013,4865080,tt4865080,crack capitalism,2015,NaN,32 min,"documentary, short",NaN,eric alexander-hughes,NaN,...,NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,2015-08-21 18:55:22.797000000
95014,4865622,tt4865622,room: the mystery,2014,NaN,90 min,thriller,2014-12-12,faisal khan,kadir sayyed,...,NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,2015-11-02 16:06:27.237000000
95015,4875364,tt4875364,driven underground,2015,NaN,90 min,"crime, drama",2015-09-04,george erschbamer,roslyn muir,...,NaN,NaN,NaN,0.0,0,NaN,NaN,odyssey media,NaN,2015-11-16 08:37:10.163000000
95016,4882694,tt4882694,kl 10 patthu,2015,NaN,130 min,"comedy, family, romance",2015-07-18,muhsin parari,muhsin parari,...,NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,2015-10-26 14:22:43.880000000
95017,4893184,tt4893184,captain,2015,not rated,149 min,"action, drama, history",2015-07-18,rob reep,"beverly reep, rob reep",...,NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,2015-11-10 10:00:13.607000000
95018,4898004,tt4898004,cinema chupista maava,2015,NaN,NaN,family,NaN,trinadha rao nakkina,prasanna kumar,...,NaN,NaN,NaN,5.0,1,NaN,NaN,NaN,NaN,2015-11-09 05:01:42.207000000
95019,4950508,tt4950508,fall of japan: in color,2015,NaN,NaN,documentary,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,2015-10-26 03:51:23.277000000
95020,4973112,tt4973112,hitting the apex,2015,NaN,138 min,documentary,2015-09-23,mark neale,mark neale,...,NaN,NaN,NaN,4.1,16,NaN,NaN,NaN,NaN,2015-10-27 02:11:12.493000000
95021,4985254,tt4985254,tigress blood,2014,NaN,44 min,documentary,2014-09-25,"praveen singh, akanksha sood",julie zastrow getz (script writer),...,NaN,NaN,NaN,0.0,0,NaN,NaN,kosmik global media private limited,NaN,2015-10-09 23:04:23.493000000
95022,5018032,tt5018032,absolute zombies,2015,NaN,75 min,horror,2015-10-27,johnny markussen,NaN,...,NaN,NaN,NaN,0.0,0,NaN,NaN,NaN,NaN,2015-10-24 17:29:56.447000000

In [28]:
omdb_tomatoes[omdb_tomatoes.otitle == 'kate and leopold']

,id,imdbid,otitle,oyear,rating,runtime,genre,released,director,writer,...,rotten,consensus,usermeter,userrating,userreviews,dvd,boxoffice,production,website,tlastupdated
4261,35423,tt0035423,kate and leopold,2001,pg-13,118 min,"comedy, fantasy, romance",2001-12-25,james mangold,"steven rogers (story), james mangold (screenpl...",...,63,"Though Jackman charms, Kate and Leopold is bla...",62,3,189445,2002-06-11,$47.1M,miramax films,http://www.kateandleopold-themovie.com,2015-10-24 17:37:45.527000000

In [29]:
tomatoes[tomatoes.website == 'http://www.kateandleopold-themovie.com']

,id,image,trating,meter,reviews,fresh,rotten,consensus,usermeter,userrating,userreviews,dvd,boxoffice,production,website,tlastupdated
4263,35423,rotten,5.3,50,126,63,63,"Though Jackman charms, Kate and Leopold is bla...",62,3,189445,2002-06-11,$47.1M,miramax films,http://www.kateandleopold-themovie.com,2015-10-24 17:37:45.527000000

In [30]:
# convert box_omdb id to numeric and merge Box, OMDB, and Tomatoes dataframes on id
box_omdb.id = box_omdb.id.convert_objects(convert_numeric=True)
bot = pd.merge(box_omdb, tomatoes, on = 'id', how = 'inner')
bot

C:\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  from ipykernel import kernelapp as app

,list_number,btitle,studio,total_gross,total_theatres,opening_gross,opening_theatres,opening_date,byear,title_year,...,rotten,consensus,usermeter,userrating,userreviews,dvd,boxoffice,production,website,tlastupdated
0,385,after earth,sony,60522097,3401,27520040,3401,2013-05-31,2013,after earth|2013,...,168,"After Earth is a dull, ploddingly paced exerci...",37,2.8,120936,2013-10-08,$60.5M,sony pictures,http://afterearth.com/,2015-10-16 17:18:35.493000000
1,6817,the hundred-foot journey,bv,54240821,2167,10979290,2023,2014-08-08,2014,the hundred-foot journey|2014,...,41,Director Lasse Hallstr�m does lovely work and ...,81,4.0,31684,2014-12-02,NaN,walt disney pictures,http://100footjourneymovie.com/,2015-10-12 17:29:22.157000000
2,31,102 dalmatians,bv,66957026,2704,19883351,2704,2000-11-22,2000,102 dalmatians|2000,...,62,This sequel to the live-action 101 Dalmatians ...,32,2.9,406269,2001-04-03,$65.4M,buena vista pictures,http://disney.go.com/DisneyPictures/102dalmatians,2015-10-25 16:49:52.500000000
3,13,10 items or less,think,83291,15,35929,15,2006-12-01,2006,10 items or less|2006,...,22,A small film that relies too heavily on the ch...,65,3.2,23814,2007-04-27,$69.3k,thinkfilm,NaN,2015-10-11 17:16:23.543000000
4,32,10th and wolf,think,54702,6,20774,6,2006-08-18,2006,10th and wolf|2006,...,22,A scattered mob movie that employs every mafia...,52,3.1,17406,2006-09-19,NaN,thinkfilm,http://www.10thandwolf.com,2015-10-25 17:40:26.150000000
5,16,10 things i hate about you,bv,38178166,2311,8330681,2271,1999-03-31,1999,10 things i hate about you|1999,...,24,Julia Stiles and Heath Ledger add strong perfo...,69,3.3,32102737,1999-10-12,NaN,buena vista pictures,NaN,2015-10-12 17:50:55.757000000
6,17,10 to midnight,mgm,7175592,595,3050225,595,1983-03-11,1983,10 to midnight|1983,...,3,NaN,52,3.0,12311,2003-02-04,NaN,mgm,NaN,2015-10-24 17:47:14.460000000
7,35,the 11th hour,wip,707343,111,60853,4,2007-08-17,2007,the 11th hour|2007,...,30,Well-researched and swimming in scientific dat...,69,3.6,29239,NaN,&#163;0.6M,warner independent pictures,http://www.11thhourfilm.com/,2015-11-03 05:25:33.717000000
8,44,127 hours,foxs,18335230,916,264851,4,2010-11-05,2010,127 hours|2010,...,15,"As gut-wrenching as it is inspirational, 127 H...",85,4.0,93637,2011-03-01,$18.3M,fox searchlight,http://www.127hoursmovie.com/,2015-10-15 17:14:33.090000000
9,41,12 rounds,fox,12234694,2331,5329240,2331,2009-03-27,2009,12 rounds|2009,...,49,"Energetic but empty, 12 Rounds' preposterous p...",45,3.2,83949,2009-06-30,$12.2M,20th century fox,http://www.12rounds-movie.com/,2015-10-20 17:37:06.440000000
10,48,13 going on 30,sonr,57231747,3453,21054283,3438,2004-04-23,2004,13 going on 30|2004,...,58,"The plot's nothing new, but Garner shows a lov...",71,3.3,652450,2006-02-07,$56.0M,sony pictures,http://www.sonypictures.com/movies/13goingon30...,2015-10-15 17:05:34.657000000
11,51,13 sins,rtwc,13809,45,9261,45,2014-04-18,2014,13 sins|2014,...,15,NaN,45,3.2,4001,2014-06-16,$9.1k,radius-twc,http://radiustwc.com/releases/13-sins/,2015-10-24 17:08:53.440000000
12,54,the 13th alley,schf.,250992,72,112946,72,2008-06-13,2008,the 13th alley|2008,...,NaN,NaN,NaN,2.8,4,NaN,NaN,NaN,http://www.the13thalleymovie.com,2015-11-03 10:49:12.450000000
13,55,the 13th warrior,bv,32698899,2313,10267756,2306,1999-08-27,1999,the 13th warrior|1999,...,58,"Atmospheric, great sets and costumes, but thin...",66,3.2,117461,2002-01-15,NaN,buena vista pictures,NaN,2015-10-24 17:18:17.670000000
14,57,1408,mgm/w,71985628,2733,20617667,2678,2007-06-22,2007,1408|2007,...,36,Relying on psychological tension rather than o...,61,3.4,744053,2007-10-02,$71.9M,mgm/dimension,http://www.1408-themovie.com/,2015-10-15 18:48:48.293000000
15,58,1492: conquest of paradise,par.,7191399,1008,3002680,1008,1992-10-09,1992,1492: conquest of paradise|1992,...,11,NaN,51,3.1,12185,2002-05-14,NaN,paramount home video,NaN,2015-10-28 01:16:43.387000000
16,61,15 minutes,nl,24403552,2337,10523154,2337,2001-03-09,2001,15 minutes|2001,...,83,As critical as it is about sensationalism in t...,38,2.9,50481,2001-08-14,$24.2M,new line cinema,http://www.15minutesmovie.com,2015-10-25 22:41:46.943000000
17,62,16 blocks,wb,36895141,2706,11855260,2706,2006-03-03,2006,16 blocks|2006,...,71,Despite strong performances from Bruce Willis ...,58,3.2,163585,2006-06-13,$36.9M,warner bros.,http://16blocks.com,2015-10-14 19:54:07.010000000
18,65,17 again,wb (nl),64167069,3255,23722310,3255,2009-04-17,2009,17 again|2009,...,64,"Though it uses a well-worn formula, 17 Again h...",67,3.6,465080,2009-08-11,$64.1M,new line cinema,http://www.17againmovie.com/,2015-10-15 17:39:40.243000000
19,72,1911,vari.,135739,33,55850,33,2011-10-07,2011,1911|2011,...,22,NaN,30,2.8,1457,2012-01-10,$0.1M,variance films,http://www.1911movie.com,2015-10-25 18:49:59.107000000
20,73,1915,bm,96682,10,30448,8,2015-04-17,2015,1915|2015,...,5,NaN,86,4.4,293,NaN,$57.6k,bloodvine media,http://www.1915themovie.com/,2015-10-29 16:25:00.497000000
21,14507,tomorrowland,bv,93436322,3972,33028165,3972,2015-05-22,2015,tomorrowland|2015,...,115,"Ambitious and visually stunning, Tomorrowland ...",52,3.3,82458,2015-10-13,$93.4M,walt disney pictures,http://movies.disney.com/tomorrowland/,2015-10-12 17:06:07.947000000
22,75,1969,atl,5979011,520,1709120,520,1988-11-18,1988,1969|1988,...,5,NaN,44,3.0,3593,2002-04-16,NaN,media home entertainment,NaN,2015-10-25 17:16:45.927000000
23,94,200 cigarettes,par.,6852450,978,3244277,976,1999-02-26,1999,200 cigarettes|1999,...,43,A clumsy and scattered comedy with a poorly ex...,59,3.0,32073,1999-08-31,NaN,paramount pictures,http://www.200cigarettes.com,2015-10-25 15:38:42.053000000
24,103,2010,mgm,40400657,1213,7393361,1126,1984-12-07,1984,2010|1984,...,11,NaN,61,3.3,25172,1998-08-25,NaN,mgm/ua entertainment company,NaN,2015-10-24 17:42:50.817000000
25,106,2012,sony,166112167,3444,65237614,3404,2009-11-13,2009,2012|2009,...,144,Roland Emmerich's 2012 provides plenty of visu...,47,3.2,507202,2010-03-02,$166.1M,sony pictures/columbia,http://www.whowillsurvive2012.com/,2015-10-13 17:30:50.747000000
26,108,2012: time for change,mang.,68339,2,9009,1,2010-04-09,2010,2012: time for change|2010,...,NaN,NaN,75,3.9,205,2012-02-21,$63.5k,curious pictures,http://www.mangu.tv/2012,2015-10-26 01:10:46.037000000
27,114,21,sony,81159365,2952,24105943,2648,2008-03-28,2008,21|2008,...,106,21 could have been a fascinating study had it ...,66,3.6,367076,2008-07-22,$81.2M,sony/columbia pictures,http://www.sonypictures.com/movies/21/,2015-10-11 17:50:27.103000000
28,115,21 and over,rela.,25682380,2771,8754168,2771,2013-03-01,2013,21 and over|2013,...,71,"Though it strives to mimic The Hangover, 21 an...",47,3.2,58524,2013-06-18,$25.7M,relativity media,http://21andovermovie.tumblr.com/,2015-10-25 16:05:18.830000000
29,116,21 grams,focus,16290476,411,274454,8,2003-11-21,2003,21 grams|2003,...,35,Alejandro Gonz�lez I��rritu deftly weaves an u...,86,3.6,209565,2004-03-16,$16.2M,universal pictures,http://www.21-grams.com/,2015-10-13 17:53:11.990000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7510,16120,youth without youth,spc,244397,18,28550,6,2007-12-14,2007,youth without youth|2007,...,71,"Although visually appealing, Coppola's latest ...",44,3.0,16846,2008-05-13,$0.1M,sony pictures classics,http://www.sonyclassics.com/youthwithoutyouth/,2015-10-24 17:52:31.270000000
7511,16080,you've got mail,wb,115821495,2948,18426749,2691,1998-12-18,1998,you've got mail|1998,...,26,Great chemistry between the leads made this a ...,73,3.1,461580,1999-05-04,NaN,warner bros. pictures,http://www.youvegotmail.com,2015-10-24 17:15:40.790000000
7512,16123,yuva,nem,331166,35,210000,30,2004-05-21,2004,yuva|2004,...,NaN,NaN,76,3.7,4500,2004-10-30,$0.3M,net effect,http://www.yuvathefilm.com,2015-10-25 19:49:13.917000000
7513,16124,yuvvraaj,eros,570090,77,264362,77,2008-11-21,2008,yuvvraaj|2008,...,NaN,NaN,33,2.9,1371,2010-01-12,$0.6M,eros multimedia pvt. ltd.,http://yuvvraaj.erosentertainment.com/,2015-10-27 21:50:34.830000000
7514,16125,yves saint laurent,wein.,723593,24,24207,2,2014-06-25,2014,yves saint laurent|2014,...,35,While it boasts its share of fine performances...,40,3.1,3049,NaN,$0.7M,the weinstein company,NaN,2015-10-16 18:45:39.663000000
7515,16130,zack and miri make a porno,wein.,31457946,2735,10065630,2735,2008-10-31,2008,zack and miri make a porno|2008,...,67,Zack and Miri Make a Porno is a modest success...,67,3.5,236197,2009-02-03,$31.4M,the weinstein company,http://zackandmiri.com/,2015-10-24 17:11:46.863000000
7516,16131,zapped!,emb,16897768,777,823548,200,1982-07-23,1982,zapped!|1982,...,13,NaN,39,2.8,5692,2008-02-12,NaN,embassy,NaN,2015-10-16 19:20:51.217000000
7517,16137,zebrahead,triu,1557771,251,609041,251,1992-10-23,1992,zebrahead|1992,...,4,NaN,69,3.3,923,2002-06-18,NaN,ixtlan corporation,NaN,2015-10-26 14:00:22.867000000
7518,16139,zelig,wb,11798616,245,60119,6,1983-07-15,1983,zelig|1983,...,0,NaN,88,3.9,18098,2001-11-06,NaN,warner home video,NaN,2015-10-26 06:38:21.070000000
7519,16142,zenith,cp,7862,4,2347,1,2010-10-01,2010,zenith|2010,...,5,NaN,39,3.0,810,2011-11-14,$7.9k,cinema purgatorio,http://www.zeniththefilm.com/,2015-10-26 01:28:25.320000000
7520,16141,the zen of bennett,abr.,NaN,NaN,NaN,NaN,2012-10-24,2012,the zen of bennett|2012,...,3,NaN,60,3.6,179,2012-11-19,NaN,abramorama entertainment,http://www.zenofbennett.com/,2015-10-26 01:03:05.450000000
7521,16145,zero charisma,trib.,9417,5,NaN,NaN,2013-10-11,2013,zero charisma|2013,...,5,NaN,56,3.3,1085,2014-05-22,NaN,tribeca film,http://www.zerocharismathemovie.com/,2015-10-25 16:20:38
7522,16147,zero day,avat.,8466,1,3148,1,2003-09-03,2003,zero day|2003,...,13,NaN,78,3.7,3498,2005-04-05,NaN,avatar films,http://www.avatarfilms.com/releases/zero_day.html,2015-10-04 18:25:24.147000000
7523,16148,zero effect,sony,2087471,129,434840,100,1998-01-30,1998,zero effect|1998,...,17,A promising debut for writer/director Jake Kas...,77,3.5,7733,1998-07-07,NaN,warner home video,NaN,2015-10-24 17:16:16.870000000
7524,16151,zero motivation,zeit.,116044,7,9427,1,2014-12-03,2014,zero motivation|2014,...,6,"Darkly funny and understatedly absurd, Zero Mo...",83,4.0,1037,2015-07-05,$0.1M,zeitgeist films,http://www.zeitgeistfilms.com/film.php?directo...,2015-10-04 17:39:23.937000000
7525,16155,zeus and roxanne,mgm,7233324,1745,2755382,1745,1997-01-24,1997,zeus and roxanne|1997,...,4,NaN,42,2.9,8943,2001-08-07,NaN,hbo video,NaN,2015-10-27 09:02:03.290000000
7526,16129,z for zachariah,ratt.,121461,29,56902,29,2015-08-28,2015,z for zachariah|2015,...,16,Z for Zachariah wrings compelling drama out of...,51,3.2,4235,2015-10-20,$0.1M,roadside attractions,NaN,2015-10-15 17:34:39.393000000
7527,16159,zinda,eros,332491,38,167246,38,2006-01-13,2006,zinda|2006,...,NaN,NaN,60,3.4,2791,2006-03-28,NaN,NaN,http://www.zindathefilm.com,2015-10-04 17:10:17.553000000
7528,16160,zindagi na milegi dobara,eros,3108485,100,960548,100,2011-07-15,2011,zindagi na milegi dobara|2011,...,0,NaN,86,4.0,3634,2011-09-26,NaN,eros international,http://www.znmdthemovie.com/,2015-10-12 19:17:58.287000000
7529,16162,zizek!,zeit.,20177,1,7062,1,2005-11-18,2005,zizek!|2005,...,5,NaN,75,3.7,891,2006-07-25,NaN,zeitgeist films,http://www.zeitgeistfilms.com/film.php?directo...,2015-09-28 18:01:03.140000000
7530,16164,zodiac,par.,33080084,2379,13395610,2362,2007-03-02,2007,zodiac|2007,...,25,"A quiet, dialogue-driven thriller that deliver...",77,3.5,490355,2007-07-24,$33.0M,paramount pictures,http://www.ZodiacMovie.com/,2015-10-11 19:21:57.793000000
7531,16165,zokkomon,utv,2815,24,2815,24,2011-04-22,2011,zokkomon|2011,...,NaN,NaN,50,3.0,77,2011-07-26,$2.8k,utv motion pictures,NaN,2015-10-10 21:10:26.033000000
7532,16168,zombie high,pec,21905,25,12165,25,1987-10-02,1987,zombie high|1987,...,NaN,NaN,4,2.3,193,1988-01-02,NaN,cinema group,NaN,2015-10-25 17:02:14.350000000
7533,16170,zombieland,sony,75590286,3171,24733155,3036,2009-10-02,2009,zombieland|2009,...,25,"Wickedly funny and featuring plenty of gore, Z...",86,3.5,639515,2010-02-02,$75.6M,sony/columbia pictures,http://www.zombieland.com/,2015-10-11 17:52:10.967000000
7534,16171,zoo,think,69770,5,7811,1,2007-04-25,2007,zoo|2007,...,20,While a marginally fascinating look at a taboo...,36,2.8,4483,NaN,NaN,thinkfilm,NaN,2015-11-02 12:22:07.403000000
7535,16172,zookeeper,sony,80360843,3482,20065617,3482,2011-07-08,2011,zookeeper|2011,...,108,Zookeeper smothers Kevin James's with a sodden...,41,3.0,44211,2011-10-11,$80.4M,columbia pictures,http://www.zookeeper-movie.net/,2015-10-15 17:46:02.907000000
7536,16173,zoolander,par.,45172250,2522,15525043,2507,2001-09-28,2001,zoolander|2001,...,47,"A wacky satire on the fashion industry, Zoolan...",81,3.3,942584,2002-03-12,$44.7M,paramount pictures,http://www.zoolander.com,2015-10-14 19:29:55.447000000
7537,16174,zoolander 2,par.,NaN,NaN,NaN,NaN,2016-02-12,2016,zoolander 2|2016,...,NaN,NaN,NaN,4.0,18366,NaN,NaN,paramount pictures,http://www.zoolander.com/,2015-11-03 01:24:47.667000000
7538,16175,zoom,sonr,11989328,2501,4510408,2501,2006-08-11,2006,zoom|2006,...,63,Lacking the punch and good cheer of The Incred...,32,2.9,11174,2007-09-02,$11.6M,sony pictures entertainment,http://www.sonypictures.com/movies/zoom/index....,2015-10-24 17:27:59.243000000
7539,8343,the legend of zorro,sony,46464023,3520,16328506,3520,2005-10-28,2005,the legend of zorro|2005,...,99,"Zorro can survive a lot of things, but it look...",48,3.2,454762,2006-01-31,$45.4M,sony pictures entertainment,http://www.sonypictures.com/movies/thelegendof...,2015-10-15 17:05:51

In [31]:
# drop unneeded columns
box_omdb = box_omdb.drop(['list_number', 'poster', 'lastupdated'], axis=1)
omdb_tomatoes = omdb_tomatoes.drop(['poster', 'lastupdated', 'website', 'tlastupdated'], axis=1)
bot = bot.drop(['list_number', 'poster', 'lastupdated', 'website', 'tlastupdated'], axis=1)

In [32]:
# create csv files for box_omdb, omdb_tomatoes, and bot dataframes
box_omdb.to_csv('box_omdb.csv', delimiter = ',')
omdb_tomatoes.to_csv('omdb_tomatoes.csv', delimiter = ',')
bot.to_csv('bot.csv', delimiter = ',')

In [33]:
# identify null values for country
# bot.country[bot.country.isnull()]

# replace null values for country with USA
bot.country.replace([np.nan], ['usa'], inplace = True)

# convert country text into feature vectors and 
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(decode_error = 'ignore')
vect.fit(bot.country)
vect.get_feature_names()

# transform country into a 'document-term matrix'
country_dtm = vect.transform(bot.country)
country_dtm.toarray() 
country_data = pd.DataFrame(country_dtm.toarray(), columns=vect.get_feature_names())
country_data.sum()

afghanistan       3
africa           24
algeria           1
and               4
arab             15
arabia            2
argentina        15
aruba             1
australia       167
austria          15
bahamas           2
belgium          26
bhutan            1
bolivia           1
bosnia            3
botswana          1
brazil           23
bulgaria          2
burkina           1
canada          400
chad              1
chile             7
china            70
colombia          2
costa             1
croatia           1
cuba              2
czech            23
denmark          31
dominican         2
               ...
rico              1
romania          11
russia           13
rwanda            1
saudi             2
serbia            2
singapore         5
slovenia          2
south            53
soviet            2
spain            67
sri               2
sweden           25
switzerland      21
taiwan            9
thailand          4
tunisia           1
turkey            6
uk              930
ukraine           3
union             2
united           15
uruguay           1
usa            6529
venezuela         2
vietnam           4
west             15
yugoslavia        5
zealand          35
zimbabwe          1
dtype: int64

In [42]:
# dummy_df=pd.get_dummies(bot['country'], prefix='country')
# dummy_df

bot_dict = {'genre':'nominal', 'director':'nominal', 'writer':'nominal', 'cast':'nominal', 'language':'nominal', 'country':'nominal'}

def dummy_variables(data, data_type_dict):
    #Loop over nominal variables.
    for variable in filter(lambda x: data_type_dict[x]=='nominal',
                           data_type_dict.keys()):
 
        #First we create the columns with dummy variables.
        #Note that the argument 'prefix' means the column names will be
        #prefix_value for each unique value in the original column, so
        #we set the prefix to be the name of the original variable.
        dummy_df=pd.get_dummies(data[variable], prefix=variable)
 
        #Remove old variable from dictionary.
        data_type_dict.pop(variable)
 
        #Add new dummy variables to dictionary.
        for dummy_variable in dummy_df.columns:
            data_type_dict[dummy_variable] = 'nominal'
 
        #Add dummy variables to main df.
        data=data.drop(variable, axis=1)
        data=data.join(dummy_df)
 
    return [data, data_type_dict]

new_df = pd.DataFrame(dummy_variables(bot, bot_dict)[0])

In [60]:
genre_list = set(bot.genre.values)
feature_prefix = "genre_"

In [70]:
def combine_features(row):
    
    new_column = []
    
    for key in genre_list:
        new_column.append(row[feature_prefix + key])
    
    return new_column
    
new_df.head(1).apply(combine_features)

NameError: ("global name 'feature_prefix' is not defined", u'occurred at index btitle')

In [35]:
box.btitle = box.btitle.astype(str)
omdb.otitle = omdb.otitle.astype(str)

import Levenshtein
from Levenshtein import distance
edit_dist = distance("13th warrior", "the 13th warrior")
print edit_dist

# titles = []
# for b in box.btitle:
#     for o in omdb.otitle.index:
#         if distance(b, omdb.otitle[o]) < 4:
#             titles.append(b)
# print titles

4

In [36]:
# 1. Is the code correct? Do we intend to think about each feature as a combination of names (e.g. usa, uk, and mexico as one feature)?
# 2. How do we get the dataframe to be viewed like one?
# 3. Now that we have 1000s of columns, does anything change in terms of how we run algorithms? 
# 4. Levenshtein - how to implement?